name: GitHub Pages

on: push

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - uses: docker://pandoc/core:2.9.2
      with:
        args: "--standalone -t revealjs -o html/index.html demo.md"
    
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html
